---
title: "Homework 2"
author: "Noah Johnson"
date: "February 17, 2018"
output: pdf_document
header-includes:
  - \usepackage{enumitem}
  - \usepackage{xcolor}
  - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(install.load)

install_load("tidyverse")
```

\newcommand{\numColor}[2] {\begingroup\color{#1} #2 \endgroup}

## Exercises

\textbf{4.2} There are two events $A$ and $B$. $P(A) = .5$ and $P(B) = .3$. The events $A$ and $B$ are independent.

\begin{enumerate}[label=(\alph*)]

\item \textbf{Find} $\mathbf{P(\tilde{A})}$

$$
P(\tilde{A}) = 1 - P(A) = 1 - 0.5 = 0.5
$$

\item \textbf{Find} $\mathbf{P(A \cap B)}$

$$
\begin{aligned}
P(A \cap B) = P(B | A) * P(A) \\
= P(B) * P(A)\ \ \  \text{(since A and B are independent)} \\
= .3 * .5 = .15
\end{aligned}
$$

\item \textbf{Find} $\mathbf{P(A \cup B)}$

$$
\begin{aligned}
P(A \cup B) = P(A) + P(B) - P(A \cap B) \\
= .5 + .3 - .15 = .65
\end{aligned}
$$

\end{enumerate}

\textbf{4.4} There are two events $A$ and $B$. $P(A) = .7$ and $P(B) = .8$. $P(\tilde{A} \cap \tilde{B}) = .1$.

\begin{enumerate}[label=(\alph*)]

\item \textbf{Are $\mathbf{A}$ and $\mathbf{B}$ independent events? Explain why or why not.}

$$
\begin{aligned}
P(A \cup B) = 1 - P(\overline{A \cup B}) \\ 
= 1 - P(\tilde{A} \cap \tilde{B})\ \ \text{ (using De Morgan's Law)} \\
= 1 - 0.1 = .9\\
\\
P(A \cap B) = P(A) + P(B) - P(A \cup B) \\
= .7 + .8 - .9 = .6 \\
\\
P(B | A) = \frac{P(A \cap B)}{P(A)} = \frac{.6}{.7} = \frac{6}{7} \\
\neq \frac{4}{5} = P(B) \ \therefore \text{A and B are not independent events.}
\end{aligned}
$$

\item \textbf{Find} $\mathbf{P(A \cup B)}$

Refer to the first equation above. $P(A \cup B) = 0.9$.

\end{enumerate}

\textbf{4.6} Two fair dice, one red and one green, are rolled. Let the event $A$ be "the sum of the faces showing is equal to seven." Let the event B be "the faces showing on the two dice are equal."

\begin{enumerate}[label=(\alph*)]

\item \textbf{List out the sample space of the experiment.}

$$
\begin{aligned}
\Omega = \{ (\numColor{red}{1}, \numColor{green}{1}), (\numColor{red}{1}, \numColor{green}{2}), (\numColor{red}{1}, \numColor{green}{3}), (\numColor{red}{1}, \numColor{green}{4}), (\numColor{red}{1}, \numColor{green}{5}), (\numColor{red}{1}, \numColor{green}{6}), \\
(\numColor{red}{2}, \numColor{green}{1}), (\numColor{red}{2}, \numColor{green}{2}), (\numColor{red}{2}, \numColor{green}{3}), (\numColor{red}{2}, \numColor{green}{4}), (\numColor{red}{2}, \numColor{green}{5}), (\numColor{red}{2}, \numColor{green}{6}), \\
(\numColor{red}{3}, \numColor{green}{1}), (\numColor{red}{3}, \numColor{green}{2}), (\numColor{red}{3}, \numColor{green}{3}), (\numColor{red}{3}, \numColor{green}{4}), (\numColor{red}{3}, \numColor{green}{5}), (\numColor{red}{3}, \numColor{green}{6}), \\
(\numColor{red}{4}, \numColor{green}{1}), (\numColor{red}{4}, \numColor{green}{2}), (\numColor{red}{4}, \numColor{green}{3}), (\numColor{red}{4}, \numColor{green}{4}), (\numColor{red}{4}, \numColor{green}{5}), (\numColor{red}{4}, \numColor{green}{6}), \\
(\numColor{red}{5}, \numColor{green}{1}), (\numColor{red}{5}, \numColor{green}{2}), (\numColor{red}{5}, \numColor{green}{3}), (\numColor{red}{5}, \numColor{green}{4}), (\numColor{red}{5}, \numColor{green}{5}), (\numColor{red}{5}, \numColor{green}{6}), \\
(\numColor{red}{6}, \numColor{green}{1}), (\numColor{red}{6}, \numColor{green}{2}), (\numColor{red}{6}, \numColor{green}{3}), (\numColor{red}{6}, \numColor{green}{4}), (\numColor{red}{6}, \numColor{green}{5}), (\numColor{red}{6}, \numColor{green}{6})\}
\end{aligned}
$$

\item \textbf{List the outcomes in } $\mathbf{A}$, \textbf{and find} $\mathbf{P(A)}$.

$A = \{ (\numColor{red}{1}, \numColor{green}{6}), (\numColor{red}{2}, \numColor{green}{5}), (\numColor{red}{3}, \numColor{green}{4}), (\numColor{red}{4}, \numColor{green}{3}), (\numColor{red}{5}, \numColor{green}{2}), (\numColor{red}{6}, \numColor{green}{1})\}$

$P(A) = \frac{6}{36} = \frac{1}{6}$

\item \textbf{List the outcomes in } $\mathbf{B}$, \textbf{and find} $\mathbf{P(B)}$.

$B = \{ (\numColor{red}{1}, \numColor{green}{1}), (\numColor{red}{2}, \numColor{green}{2}), (\numColor{red}{3}, \numColor{green}{3}), (\numColor{red}{4}, \numColor{green}{4}), (\numColor{red}{5}, \numColor{green}{5}), (\numColor{red}{6}, \numColor{green}{6})\}$

$P(B) = \frac{6}{36} = \frac{1}{6}$

\item \textbf{List the outcomes in } $\mathbf{A \cap B}$, \textbf{and find} $\mathbf{P(A \cap B)}$.

$A \cap B = \varnothing$

$P(A \cap B) = 0$

\item \textbf{Are the events} $\mathbf{A}$ \textbf{and} $\mathbf{B}$ \textbf{independent? Explain why or why not.}

$$
\begin{aligned}
P(B | A) = \frac{P(A \cap B)}{P(A)} = \frac{0}{1/6} = 0\\
\neq \frac{1}{6} = P(B)\ \therefore \text{A and B are not independent events.}
\end{aligned}
$$

\item \textbf{How would you describe the relationship between event} $\mathbf{A}$ \textbf{and event} $\mathbf{B}$\textbf{?}

As mutually exclusive, since one event occurring precludes the other.

\end{enumerate}

\textbf{4.8} Two dice are rolled. The red die has been loaded. Its probabilities are $P(1) = P(2) = P(3) = P(4) = \frac{1}{5}$ and $P(5) = P(6) = \frac{1}{10}$. The green die is fair. Let the event $A$ be "the sum of the faces showing is an even number." Let the event B be "the sum of the faces showing is divisible by 3."

\begin{enumerate}[label=(\alph*)]

\item \textbf{List the outcomes in } $\mathbf{A}$, \textbf{and find} $\mathbf{P(A)}$.


\begin{multline*}
A = \{ (\numColor{red}{1}, \numColor{green}{1}), (\numColor{red}{1}, \numColor{green}{3}), (\numColor{red}{1}, \numColor{green}{5}), (\numColor{red}{2}, \numColor{green}{2}), (\numColor{red}{2}, \numColor{green}{4}), (\numColor{red}{2}, \numColor{green}{6}), (\numColor{red}{3}, \numColor{green}{1}), (\numColor{red}{3}, \numColor{green}{3}), (\numColor{red}{3}, \numColor{green}{5}), (\numColor{red}{4}, \numColor{green}{2}), (\numColor{red}{4}, \numColor{green}{4}), (\numColor{red}{4}, \numColor{green}{6}), \\
(\numColor{red}{5}, \numColor{green}{1}), (\numColor{red}{5}, \numColor{green}{3}), (\numColor{red}{5}, \numColor{green}{5}), (\numColor{red}{6}, \numColor{green}{2}), (\numColor{red}{6}, \numColor{green}{4}), (\numColor{red}{6}, \numColor{green}{6}) \}
\end{multline*}

Since the event A can be thought of as the union of all of its outcomes, and each outcome involves two independent die rolls, we can calculate P(A) as so:

$$
P(A) = \sum\limits_{E_A \in A} P(E_A) \\
= 12 * \frac{1}{30} + 6 * \frac{1}{60} = \frac{1}{2}
$$

\item \textbf{List the outcomes in } $\mathbf{B}$, \textbf{and find} $\mathbf{P(B)}$.

\begin{multline*}
B = \{ (\numColor{red}{1}, \numColor{green}{2}), (\numColor{red}{1}, \numColor{green}{5}), (\numColor{red}{2}, \numColor{green}{1}), (\numColor{red}{2}, \numColor{green}{4}), (\numColor{red}{3}, \numColor{green}{3}), (\numColor{red}{3}, \numColor{green}{6}), (\numColor{red}{4}, \numColor{green}{2}), (\numColor{red}{4}, \numColor{green}{5}), (\numColor{red}{5}, \numColor{green}{1}),
(\numColor{red}{5}, \numColor{green}{4}), (\numColor{red}{6}, \numColor{green}{3}),
(\numColor{red}{6}, \numColor{green}{6})\}
\end{multline*}

Since the event B can be thought of as the union of all of its outcomes, and each outcome involves two independent die rolls, we can calculate P(B) as so:

$$
P(B) = \sum\limits_{E_B \in B} P(E_B) \\
= 8 * \frac{1}{30} + 4 * \frac{1}{60} = \frac{1}{3}
$$

\item \textbf{List the outcomes in } $\mathbf{A \cap B}$, \textbf{and find} $\mathbf{P(A \cap B)}$.

$$
A \cap B = \{ (\numColor{red}{1}, \numColor{green}{5}), (\numColor{red}{2}, \numColor{green}{4}), (\numColor{red}{3}, \numColor{green}{3}), (\numColor{red}{4}, \numColor{green}{2}), (\numColor{red}{5}, \numColor{green}{1}),
(\numColor{red}{6}, \numColor{green}{6})\}
$$

$$
P(A \cap B) = \sum\limits_{E \in A \cap B} P(E) \\
= 4 * \frac{1}{30} + 2 * \frac{1}{60} = \frac{1}{6}
$$

\item \textbf{Are the events} $\mathbf{A}$ \textbf{and} $\mathbf{B}$ \textbf{independent? Explain why or why not.}

$$
\begin{aligned}
P(B | A) = \frac{P(A \cap B)}{P(A)} = \frac{1/6}{1/2} = \frac{1}{3} \\
= \frac{1}{3} = P(B)\ \therefore \text{A and B are independent events.}
\end{aligned}
$$

\end{enumerate}

\textbf{4.10} Suppose there is a medical screening procedure for a specific cancer that has \textit{sensitivity} = .90, and \textit{specificity} = .95. Suppose the underlying rate of the cancer in the population is .001. Let $B$ be the event "the person has that specific cancer," and let $A$ be the event "the screening procedure gives a positive result."

\begin{enumerate}[label=(\alph*)]

\item \textbf{What is the probability that a person has the disease given the results of the screening is positive?}

We have $P(A|B)$ (the sensitivity) and $P(\tilde{A} | \tilde{B})$ (the specificity). We also know $P(B)$ (the underlying rate). We are interested in finding $P(B|A)$.

Our first instinct is to use Bayes' Rule to flip the condition. 

$$
P(B|A) = \frac{P(A|B) * P(B)}{P(A)}
$$

However, we don't know $P(A)$, so it looks like we're stuck. Thankfully the specificity will help us out.

$$
\begin{aligned}
P(A) = P(A \cap B) + P(A \cap \tilde{B}) \\
= P(A|B) * P(B) + P(A|\tilde{B}) * P(\tilde{B})
\end{aligned}
$$

From the underlying rate, $P(\tilde{B}) = 1 - P(B) = 1 - .001 = .999$.

And from the specificity, $P(A|\tilde{B}) = 1 - P(\tilde{A}|\tilde{B}) = 1 - .95 = .05$.

Now we have all the pieces:

$$
\begin{aligned}
P(A) = P(A|B) * P(B) + P(A|\tilde{B}) * P(\tilde{B}) \\
= .9 * .001 + .05 * .999 = .05085\\
\\
P(B|A) = \frac{P(A|B) * P(B)}{P(A)} = \frac{.9 * .001}{.05085} \approx .0177
\end{aligned}
$$

So given a positive result from the medical screening, the probability that a person has that specific cancer is only around 1.77\%. Very low!

\item \textbf{Does this show that screening is effective in detecting this cancer?}

No, since even with a positive screening result, it is more likely that a person does not have this specific cancer than that they do. A positive screening does raise the probability of having the cancer by an order of magnitude, but since the initial probability was so low, this isn't too helpful. Medical researchers should focus on raising the specificity of the screening, in order to make it effective.

\end{enumerate}
